config/routes.rb
SchoolNews::Application.routes.draw do
  root "static_pages#home"
  match '/help', to: "static_pages#help", via: 'get'
  match '/contact', to: "static_pages#contact", via: 'get'
  match '/about', to: "static_pages#about", via: 'get'
  match '/stack', to: "blocks#index", via: 'get'

  resources :blocks do
     resources :comments
   end
  get 'tags/:tag', to: 'blocks#index', as: :tag
  get 'reqs/:req', to: 'blocks#index', as: :req

end

app/models/block.rb
class Block < ActiveRecord::Base
	acts_as_taggable
	acts_as_taggable_on :reqs

	has_many :comments, dependent: :destroy
	mount_uploader :image, ImageUploader
	#makes sure there is an appropriate block title
	validates :title, presence: true, length: {minimum: 3}
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :block
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


	def help
	end

	def contact
	end

	def index
	end
end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController

#authenticate for deleting
	http_basic_authenticate_with name: "tom", password: "freska1234", except: [:index, :show]

#makes a new block object
	def new
		@block = Block.new
	end

#creates a block ; if saves, make new block; if not, just render 'new' view page.
	def create
		@block = Block.new(block_params)

		if @block.save
			redirect_to blocks_path
		else
			render 'new'
		end

	end

#destroying article appropriately
	def destroy
		@block = Block.find(params[:id])
		@block.destroy

		redirect_to blocks_path
	end

#update action after edit is made
	def update
		@block = Block.find(params[:id])

		if @block.update(block_params)
			redirect_to blocks_path
		else
			render 'edit'
		end
	end

#Lists blocks by tags
	def index
		if params[:tag]
			@blocks = Block.tagged_with(params[:tag])
		else
			@blocks = Block.all
		end
	end

#Lists blocks by reqs
	def reqindex
		if params[:req]
			@blocks = Block.tagged_with(params[:req])
		else
			@blocks = Block.all
		end
	end

#edits existing blocks
	def edit
		@block = Block.find(params[:id])
	end

#shows individual block
	def show
		@block = Block.find(params[:id])
	end

#defines strong block parameters so only appropriate data is passed
	private
		def block_params
			params.require(:block).permit(:title, :text, :tag_list, :req_list, :todo,:image, :remote_image_url)
		end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	#authenticate deleting comments
	http_basic_authenticate_with name: "tom", password: "freska1234", only: :destroy

	#creating comment
	def create
		@block = Block.find(params[:block_id])
		@comment = @block.comments.create(comment_params)
		redirect_to block_path(@block)
	end

	def destroy
		@block = Block.find(params[:block_id])
		@comment = @block.comments.find(params[:id])
		@comment.destroy
		redirect_to block_path(@block)
	end

	private
		def comment_params
			params.require(:comment).permit(:commenter, :body)
		end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def contact
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
	def cash
		return "money, "
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/blocks/_form.html.erb
<%= form_for @block, :html => {:multipart => true} do |b| %>
	<% if @block.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@block.errors.count, "error") %> prohibited this block from being saved:
			</h2>
			<ul>
			<% @block.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<%end%>

	<p>
		<%= b.label :title %><br>
		<%= b.text_field :title %>
	</p>

	<p>
		<%= b.label :tags %><br>
		<%= b.text_field :tag_list, { :placeholder => "Separate Tags By Commas" } %><br>
		
		<%= b.check_box :req_list %>Needs 21-ID<br>
		<%= b.check_box :req_list %>Needs Money<br>
		<%= b.check_box :req_list %>Needs Car<br>
		
	</p>

	<p>
		<%= b.label :text %><br>
		<%= b.text_area :text %><br>

	</p>
	<p>
		<%=b.file_field :image %>
	</p>
	<p>
		<%= b.label :remote_image_url, "or image URL" %><br/>
		<%= b.text_field :remote_image_url %>
	</p>
		<label>
			<%= b.check_box :remove_image %>
			Remove Image
		</label>
	<p>
		<%= b.submit %>
	</p>

<% end %>

app/views/blocks/edit.html.erb
<div id="indent">
<h1> Editing Block </h1>

<%= render 'form' %>

<%= link_to 'Back', blocks_path %>
</div>

app/views/blocks/index.html.erb
<div id="padded">
<div id="blockheader"> <%= link_to 'Add List Item', new_block_path %>
<br>


<div id='tag_cloud'>
	<% tag_cloud Block.tag_counts, %w[s m l] do |tag, css_class| %>
		<%= link_to tag.name, tag_path(tag.name), class: css_class %>
	<% end %>
</div>

</div>

<br>
<div class="titleband">
<span class="tdtitle"> To-Do </span>
<span class= "ctitle"> Completed </span>
</div>	
<br>


<% @blocks.each do |block| %>
	<span>
		<div id="block">
			<p class="center">
			<%= link_to block.title, block_path(block) %>
			</p>
			<p id="tags">
				<%= raw block.tag_list.map { |t| link_to t, tag_path(t) }.join('     ') %>
			</p>
		</div>
	</span>
	<br>
<% end %>
<br>
</div>

app/views/blocks/new.html.erb
<div id="indent">
<h1> New Block </h1>

<%= render 'form' %>

<%= link_to 'Back to Stack', blocks_path %>
</div>

app/views/blocks/show.html.erb
<div id="extrapadded">
<br>
<div id="bigblock">

		<h2 class="center" >
			<%= @block.title %>
		</h2>
		<p>
		<!-- image_tag block.image_url(:thumb) if block.image?-->
		</p>
		<p>
		Text:
		<%= @block.text %>
		</p>
		<p id="tags">
		Tags:
		<%= @block.tag_list %>
		</p>
		<p id="reqs">
		Reqs:
		<%= @block.req_list %>
		</p>
		<p>
		</p>

</div>

<%= render @block.comments %>

<h2>Comment:</h2>
<%= render "comments/form" %>
		

<%= link_to 'Back', blocks_path %> |
<%= link_to 'Edit', edit_block_path(@block) %> |
<%= link_to 'Delete', @block, :method => :delete, data: {confirm: 'You Sure Bro?'}  %>

</div>

app/views/comments/_comment.html.erb
<br>
<div id="commentblock">
	<h3>
		<%= comment.commenter %>
	</h3>
	<p>
		<%= comment.body %>
		<br>
		<%= link_to 'Delete', [comment.block, comment], method: :delete, data: {confirm: 'You sure Bro?' } %>
	</p>
</div>

app/views/comments/_form.html.erb
<%= form_for([@block, @block.comments.build]) do |b| %>
	<p>
		<%= b.label :commenter %><br>
		<%= b.text_field :commenter %>
	</p>
	<p>
		<%= b.label :body %><br>
		<%= b.text_area :body %>
	</p>
	<p>
		<%= b.submit %>
	</p>
<% end %>

app/views/layouts/_header.html.erb
<header>
	<span class="logo">
		<%= link_to 'RPI Bucket List 2011-2015', blocks_path, {:class =>"sunken"} %>
	</span>
	<span class="headerlinks"> 		
		<%= link_to 'About', about_path, {:class =>"sunken"} %>

		<%= link_to 'Contact', contact_path, {:class =>"sunken"} %>

		<%= link_to 'Home', root_path, {:class =>"sunken"} %>
	</span>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		  <title>RPI BucketList</title>
		  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		  <%= csrf_meta_tags %>
		  <link rel="shortcut icon" href="/assets/images/favicon.ico"/>
	</head>
	
	<body>
		<div id="wrapper">
			<div id="header">
				<%= render 'layouts/header' %>
			</div>
			<div id="content">
				<%= yield %>
			</div>
			<div id="footer">
				<%= render 'layouts/footer' %>
			</div>
		</div>
	</body>
</html>

app/views/static_pages/about.html.erb
<div id="container">
	<div class="title">
		Organize Your Goals..
	</div>

	<div class="vert spacing"> 
		..To Achieve Your Dreams
	</div>
</div>

app/views/static_pages/contact.html.erb
<div id="middlecontainer">
	<div class="name">
		Tom Yang
	</div>
	<div class="clip-circle">
	</div >
	<div class="center">

	<div class= "resume">
	RPI Undergraduate Computer Systems Engineering 2015
	<br>
	yangl8@rpi.edu
	<br>
	<a href="http://tboneyang.github.io" class="static2nd">
		Blog
	</a>
	</div>
	<div>	
		<%= link_to(image_tag("twitter.jpg"), "https://twitter.com/TomLYang") %>

		<%= link_to(image_tag("facebook.jpg"), "https://www.facebook.com/thomas.l.yang") %>
	</div>
	</div>

</div>

app/views/static_pages/help.html.erb
<h4 >Help</h4>
<p>
	Send all inquiries to Tom Yang.

	LifeBlocks will get back to you as soon as possible. Thanks!
</p>

app/views/static_pages/home.html.erb
<div class="center wedged">
<h3 >Sort, Navigate, and Conquer</h3>

<h4>
<%= link_to"RPI Undergraduate Bucket List 2011-2015", blocks_path%>
<span id="content"><%= image_tag("rpi.jpg")%></span>
<div id='tag_cloud'>
	<% tag_cloud Block.tag_counts, %w[s m l] do |tag, css_class| %>
		<%= link_to tag.name, tag_path(tag.name), class: css_class %>
	<% end %>
</div>
</h4>
</div>